### ISSUE TITLE
Latest Release - Assertion Failed

### ISSUE THREAD

**Issue by Dredsen** [Qvin0000/ExileApi#105]
![image](https://user-images.githubusercontent.com/24421368/76672123-e58a2580-6570-11ea-93c9-79b3693501f2.png)

**Comment by elvese** [comment]
Same here

**Comment by awaky** [comment]
Launch the loader,exe and then launch the game, that fixes it,

**Comment by Qvin0000** [comment]
My mistake i should doesn't public this release because TehCheat now sell hud.
This can be fixed easy but now i dont anymore do any update.
