### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by kinkaito** [Qvin0000/ExileApi#13]
![image](https://user-images.githubusercontent.com/31541540/64477962-78e53700-d199-11e9-91f1-7c18eda907ed.png)

I get this error whenever i load, Did i miss something on the Release? =o
Btw Thanks for a new type of hud! :>

**Comment by hunk3r** [comment]
Hello. I have another Loader.exe error:
2019-09-07 23:22:51.585 +02:00 [Error] Loader -> System.Reflection.TargetInvocationException: Адресат вызова создал исключение. ---> System.TypeLoadException: Не удалось загрузить тип "System.ValueTuple`2" из сборки "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089".
   в Exile.Core..ctor(RenderForm form)
   --- Конец трассировки внутреннего стека исключений ---
   в System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   в System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   в System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   в System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   в System.Activator.CreateInstance(Type type, Object[] args)
   в Loader.Program.Main(String[] a) в A:\Work\BitBucket\ExileApi\Loader\Program.cs:строка 77

**Comment by TehCheat** [comment]
This was due to his personal config being included in the repo. It's not part of releases now.
