### ISSUE TITLE
stashie settings not saved

### ISSUE THREAD

**Issue by loleriz** [Qvin0000/ExileApi#14]
When changing which tabs stashie uses, if the hud is closed and then reopened, the stash tab settings in stashie revert back to what they were before. Will test manually changing them somehow, but right now this is how it's acting.

**Comment by loleriz** [comment]
Manually editing the settings for stashie under PoeHelper\config\global works.

**Comment by Hassliebe** [comment]
https://i.imgur.com/JFhXBYk.png

I can't even set them ingame. Thought we were supposed to edit them manually. Anything im missing ? :D

**Comment by loleriz** [comment]
@Hassliebe You might have a bad version there mate. Try redownloading. this is what mine looks like
![rmQMr6G](https://user-images.githubusercontent.com/2032606/64481421-6ff86380-d1a1-11e9-9cfb-c7b6a5b6ae7c.png)

there's files in PoeHelper\config\global and PoeHelper\Plugins\Compiled\Stashie, be sure both of those directories exist.

**Comment by Hassliebe** [comment]
they both do. as i said when i manually edit stashie_settings.json its working flawlessly. well :D

**Comment by kabrok** [comment]
I can't even run the loader.exe
Is there any place with instructions? Thanks.

**Comment by loleriz** [comment]
just tested, this is fixed with the newest version. Thank you all for your hard work! 😄
