### ISSUE TITLE
How do i even run this?

### ISSUE THREAD

**Issue by Laiq91** [Qvin0000/ExileApi#15]
Topic,

Now that poehud is going into retirement we have to use this which is praised by TehCheat.

But how do i start it? Read a bit about compiling but i have no clue how to do it.

Would love some help :)

Best Regards.

**Comment by Celuni** [comment]
F5

**Comment by loleriz** [comment]
Click on code on here, click on releases on here, extract the .7z file to any folder, then run Loader.exe

**Comment by Laiq91** [comment]
Thank you so much :D
