### ISSUE TITLE
Slow down stashie

### ISSUE THREAD

**Issue by thedoge3** [Qvin0000/ExileApi#16]
Setting the delay doesn't seem to slow down stashie at all. Is it possible to do that?

**Comment by loleriz** [comment]
It might if you edit the settings files manually. There seems to be an issue with saving configurations with this hud at the moment (as far as I've seen, at least)

**Comment by thedoge3** [comment]
It seems like the delay does increase the time that it takes to change between tabs, but not the dumping of items into the tabs. I also tried to increase it manually in the  Stashie_Settings.json file but no luck, same with the moust step option.

**Comment by hunk3r** [comment]
Find this string and change value to 150+
  "MouseSpeed": {
    "Value": 150

**Comment by thedoge3** [comment]
Sounds good, I will try to make it higher. I set it at exactly 150 and didn't notice a different (from the defaul 10 I think it was at?)  Will close if it works.

**Comment by thedoge3** [comment]
No luck, at least for me on the latest rev. I updated that like to 400 and noticed no change.

**Comment by hunk3r** [comment]
yeah, need to add extra-delay to settings in .cs file, dunno how to make it

**Comment by thedoge3** [comment]
closing, looks like recent update fixed it.
