### ISSUE TITLE
GameOffsets refrence

### ISSUE THREAD

**Issue by dukenuking** [Qvin0000/ExileApi#24]
Just to let you know this project can't be build because the GameOffsets lib is not present, and to compile it you also need it :), workaround is of course to just get one from the release version.
https://github.com/Qvin0000/ExileApi/blob/f61c700ab9ec76d474935ed0bdece89b228144e0/Loader/Program.cs#L71

**Comment by zaafar** [comment]
Agree with that ^. Hopefully  Qvin will fix the compiler process.

FYI to compile the new GameOffsets lib just run the "Offsets.bat" file.

**Comment by Qvin0000** [comment]
1) Download project.
2) Open ExileApi.sln
3) Unload Core
4) Compile Loader
5) Copy GameOffsets in folder with Loader.exe
6) Start Loader.exe with argument "offset" or "offsets" (release folder have bat file for this)
7) Load Core and add reference to ImGui.dll and GameOffsets.dll
Now you can compile all project
