### ISSUE TITLE
loader.exe

### ISSUE THREAD

**Issue by DlxTheSlayer** [Qvin0000/ExileApi#27]
cant run loader exe
notning happen after i trying to launch
added  loadFromRemoteSources enabled="true"   into loader.exe config and its finally work
but setting resets after every launch, core.dll crashing(doesnt respond) after 10 minutes

System.IO.FileLoadException: Не удалось загрузить файл или сборку "file:///C:\Users\Дмитрий\Desktop\secret\new\PoeHelper\Core.dll" либо одну из их зависимостей. Операция не поддерживается. (Исключение из HRESULT: 0x80131515)
Имя файла: 'file:///C:\Users\Дмитрий\Desktop\secret\new\PoeHelper\Core.dll' ---> System.NotSupportedException: Предпринята попытка загрузить сборку из сетевого ресурса, что в предыдущих версиях .NET Framework могло привести к помещению сборки в "песочницу". Этот выпуск .NET Framework не включает политику CAS по умолчанию, поэтому данная загрузка может быть опасной. Если эта нагрузка не предназначена для изоляции сборки, включите переключатель loadFromRemoteSources. Дополнительные сведения см. на странице http://go.microsoft.com/fwlink/?LinkId=155569.
   в System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   в System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   в System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   в System.Reflection.Assembly.LoadFrom(String assemblyFile)
   в Loader.Program.Main(String[] a)

**Comment by hunk3r** [comment]
Same here(

**Comment by zaafar** [comment]
Duplicate & resolved already: https://github.com/Qvin0000/ExileApi/issues/21
