### ISSUE TITLE
Can’t deactivate self healthbar.

### ISSUE THREAD

**Issue by KhaliDAlNassaj** [Qvin0000/ExileApi#38]
Can’t deactivate healtbar for self character, even deactivate players bar.
Need option for fix that maybe.

**Comment by stampis** [comment]
You have a outdated version of the HealthBar plugin.
The updated one is not pre-compiled (i think?) but can be found here:
https://github.com/Qvin0000/HealthBars

**Comment by KhaliDAlNassaj** [comment]
You right, but after test, do not show bar on minions seems. Or its only me?

**Comment by KhaliDAlNassaj** [comment]
Solved already!
