### ISSUE TITLE
Where can I find plugins

### ISSUE THREAD

**Issue by jaff095** [Qvin0000/ExileApi#45]
I tried to use the newest release.  While I found plugins like stashie and others, but I cant find basic plugs like FlaskManager which came with previous version

**Comment by stampis** [comment]
https://github.com/Qvin0000?tab=repositories

They each have their own repo.

**Comment by jaff095** [comment]
I looked there, but I still can not find flask manager.  The basicflaskroutine from old hub does not work either.

**Comment by DaxxTrias** [comment]
you can gave a precompiled version of flask manager from one of the older releases.

**Comment by username1001101** [comment]
What older releases do you mean?

**Comment by DaxxTrias** [comment]
https://github.com/Qvin0000/ExileApi/releases

Scroll down like, 4 ticks.

**Comment by TehCheat** [comment]
This is for issues with the program, not for asking questions like where plugins can be downloaded, etc.
