### ISSUE TITLE
Hud MiniMap Icons are not aligned

### ISSUE THREAD

**Issue by KeyboardCrusader** [Qvin0000/ExileApi#63]
The minimap icons in the hud do not correspond to the actual location of the player character or enemies on the map.
My naive attempt to solve this suggests this is a problem in GameWindow.cs .  Possibly it is due to a hardcoded value for the window border being included in the gathering of window size data.

**Comment by SadicVicious** [comment]
where i find the minimap monsters plugin?

**Comment by KeyboardCrusader** [comment]
This issue was not related to ExileAPI.  It was fixed for Windows 10 by doing the following:
Display Settings (right click on desktop, select 'Display Settings')
Should be on 'Display', if not choose select from left side menu
Change 'Scale and Layout' to 100%
