### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by 3v1lman** [Qvin0000/ExileApi#70]
I'm getting the following error when trying to start the HUD after building from the latest source (8280589aa9e27e6e9aa3a5a4be4d304851b061cd):
`[Error] Core constructor -> System.NullReferenceException: Object reference not set to an instance of an object.
at ExileCore.Core..ctor(RenderForm form)`

**Comment by Dragomitch** [comment]
If you find a solution for this one, I'm also interested

**Comment by 3v1lman** [comment]
This error only appears when trying to run the HUD while the game is not running for me, when starting the HUD with the game already running everything works fine.
