### ISSUE TITLE
Item:Map offsets need to updated

### ISSUE THREAD

**Issue by Murdoc84** [Qvin0000/ExileApi#71]
Hud does not recognize Item:Map during PickIt or Stashie action, when map is on the ground pickit does not work, same when map is in inventory stashie does not work. When i manually pickit map from ground then Pickit plugin start to work, and when i move manually map from inventory to stash, stashie start to work

**Comment by Shooshka** [comment]
Seems fixed with last commit

**Comment by Murdoc84** [comment]
> Seems fixed with last commit

confirm :)
