### ISSUE TITLE
SharpDX DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved

### ISSUE THREAD

**Issue by develBuzz** [Qvin0000/ExileApi#87]
I'm using a  notebook with 2 graphic adapter.   ExileApi-Output (windows and text) is distorted and not readable.  

Log error: 

bei SharpDX.Result.CheckError() in C:\projects\sharpdx\Source\SharpDX\Result.cs:Zeile 195.
   bei SharpDX.DXGI.SwapChain.Present(Int32 syncInterval, PresentFlags flags) in C:\projects\sharpdx\Source\SharpDX.DXGI\SwapChain.cs:Zeile 133.
   bei ExileCore.RenderQ.DX11.Render(Double sleepTime, Core core) in A:\Work\GitHub\ExileApi\Core\RenderQ\DX11.cs:Zeile 280.
2019-11-13 02:21:53.725 +01:00 [Error] DX11.Render -> SharpDX.SharpDXException: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved] Message: Die GPU-Geräteinstanz wurde angehalten. Verwenden Sie GetDeviceRemovedReason, um die erforderliche Aktion zu bestimmen.

(last sentence: GPU instance has stopped, use GetDeviceRemovedReason to determine action.)

Any ideas?

**Comment by jorgelpjr** [comment]
well i just start to learn about visual basic 1 day ago, but i use a notebook, with 2 graphic adapter, and run the poehud very well, no problems, just some little bugs...
if u want to test my build u can add-me on discord
JorgeLPJ
#1432

**Comment by develBuzz** [comment]
so you made changes to the source code? Mind to share them here?

**Comment by jorgelpjr** [comment]
no, i just open the project on VB, add the plugins i want, make a build and run .-.
but i will share the link herer
u just need extract all files, open the loader on exileapi/poehud/loader.exe

https://www.mediafire.com/file/ql6c6ceszl9j2n0/exileapi.rar/file
try this one...

**Comment by jorgelpjr** [comment]
tell me if u get any problem ;3

**Comment by develBuzz** [comment]
Ty for your help, i already tried another build with same results, even self-compiling without plugins wasn't successful. 

But finally solved it with a few steps: 
1) Monitor was @59 Hz while HUD was rendering @60 Hz, guess that was the reason for flickering.  Recompiled HUD with 59 HZ for the swapchain does the job (or change monitor refresh rate to 60 ofc)
2) plugins only work correct if: 
a) screen: current resolution == recommended resolution == in-game resolution  (else at least healthbars are positioned wrong)
b) scaling set to 100%

**Comment by develBuzz** [comment]
Since this workaround does it's job, i'm going to close this issue.
